apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: backup-egress-postgres
  namespace: chronicle
  labels:
    app.kubernetes.io/name: chronicle-local-backup
    app.kubernetes.io/part-of: chronicle
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: chronicle-local-backup
  policyTypes:
    - Egress
  egress:
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: kube-system
      ports:
        - protocol: UDP
          port: 53
        - protocol: TCP
          port: 53
    - to:
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: chronicle-postgres
      ports:
        - protocol: TCP
          port: 5432
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: postgres-ingress-backup
  namespace: chronicle
  labels:
    app.kubernetes.io/name: chronicle-local-backup
    app.kubernetes.io/part-of: chronicle
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: chronicle-postgres
  policyTypes:
    - Ingress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: chronicle-local-backup
      ports:
        - protocol: TCP
          port: 5432
