[PARSER]
    Name        chronicle_json
    Format      json
    Time_Key    timestamp
    Time_Keep   On

[PARSER]
    Name        chronicle_postgres
    Format      regex
    Regex       ^chronicle_pg timestamp_ms=(?<timestamp_ms>[0-9]+) sqlstate=(?<sqlstate>[0-9A-Z]{5}) (?<severity>[A-Z]+):
