// Generated by scripts/generate-chronicle-contracts.py from ontology/chronicle.linkml.yaml.
// Source-SHA256: b58054ed39ff7530d98e10fac469488db33b4fea5725a90ff6efbb804ff6ed18
// Do not edit by hand.

package chronicledeploy

#DeploymentProfile: "compose_transition" | "k8s_production" | "k8s_rhel9_small" | "k8s_rhel9_standard" | "k8s_rhel9_observability_colocated"
deploymentProfiles: [
  "compose_transition",
  "k8s_production",
  "k8s_rhel9_small",
  "k8s_rhel9_standard",
  "k8s_rhel9_observability_colocated",
]

#ObservabilityBackend: "victoria_metrics" | "victoria_logs" | "external_institutional"
observabilityBackends: [
  "victoria_metrics",
  "victoria_logs",
  "external_institutional",
]

#SourceDeviceType: "None" | "Android" | "Ios"
sourceDeviceTypes: [
  "None",
  "Android",
  "Ios",
]

#ParticipantDataType: "UsageEvents" | "Preprocessed" | "AppUsageSurvey" | "IOSSensor" | "AndroidSensor" | "SensorAvailability" | "BatteryTelemetry" | "InteractionEvents" | "AudioActivity" | "AudioContent" | "NotificationActivity" | "SleepEvents" | "ActivityRecognition" | "HealthMetrics" | "ConnectivityState" | "AppNetworkUsage" | "DeviceSettings"
participantDataTypes: [
  "UsageEvents",
  "Preprocessed",
  "AppUsageSurvey",
  "IOSSensor",
  "AndroidSensor",
  "SensorAvailability",
  "BatteryTelemetry",
  "InteractionEvents",
  "AudioActivity",
  "AudioContent",
  "NotificationActivity",
  "SleepEvents",
  "ActivityRecognition",
  "HealthMetrics",
  "ConnectivityState",
  "AppNetworkUsage",
  "DeviceSettings",
]

#ParticipationStatus: "ENROLLED" | "NOT_ENROLLED" | "PAUSED" | "COLLECTION_COMPLETED" | "UNKNOWN"
participationStatuses: [
  "ENROLLED",
  "NOT_ENROLLED",
  "PAUSED",
  "COLLECTION_COMPLETED",
  "UNKNOWN",
]

#StudyLifecycleStatus: "ACTIVE" | "ARCHIVED" | "SCHEDULED_FOR_DELETION"
studyLifecycleStatuses: [
  "ACTIVE",
  "ARCHIVED",
  "SCHEDULED_FOR_DELETION",
]

#ConsentTrigger: "ENROLLMENT" | "PARTICIPANT_TOGGLE" | "SETTINGS_CHANGE" | "WITHDRAWAL"
consentTriggers: [
  "ENROLLMENT",
  "PARTICIPANT_TOGGLE",
  "SETTINGS_CHANGE",
  "WITHDRAWAL",
]

#CollectionDataDisposition: "flush_then_stop" | "discard_and_stop" | "hold_pending"
collectionDataDispositions: [
  "flush_then_stop",
  "discard_and_stop",
  "hold_pending",
]

#CollectionPrivacyClass: "BEHAVIORAL_METADATA" | "DEVICE_STATE_METADATA" | "PHYSICAL_TELEMETRY" | "LOCAL_PARTICIPANT_LABEL" | "OPERATIONAL_DIAGNOSTICS" | "DEVICE_CAPABILITY" | "MEDIA_CONTENT" | "INTERACTION_METADATA" | "GAZE_TELEMETRY" | "SCREEN_CONTENT" | "PRECISE_LOCATION" | "HEALTH_METRICS" | "AMBIENT_AUDIO_CONTEXT" | "COMMUNICATION_METADATA"
collectionPrivacyClasses: [
  "BEHAVIORAL_METADATA",
  "DEVICE_STATE_METADATA",
  "PHYSICAL_TELEMETRY",
  "LOCAL_PARTICIPANT_LABEL",
  "OPERATIONAL_DIAGNOSTICS",
  "DEVICE_CAPABILITY",
  "MEDIA_CONTENT",
  "INTERACTION_METADATA",
  "GAZE_TELEMETRY",
  "SCREEN_CONTENT",
  "PRECISE_LOCATION",
  "HEALTH_METRICS",
  "AMBIENT_AUDIO_CONTEXT",
  "COMMUNICATION_METADATA",
]

#CollectionModuleId: "usage_events" | "in_app_activity_class" | "device_lifecycle" | "user_identification" | "upload_telemetry" | "sensor_availability" | "questionnaire" | "battery_telemetry" | "sensor_accelerometer" | "sensor_gyroscope" | "sensor_magnetometer" | "sensor_gravity" | "sensor_linear_acceleration" | "sensor_rotation_vector" | "sensor_step_counter" | "sensor_light" | "sensor_proximity" | "sensor_significant_motion" | "sensor_tilt_detector" | "sensor_screen_orientation" | "sensor_samsung_grip_wifi" | "sensor_samsung_motion" | "interaction_events" | "audio_activity" | "audio_content" | "notification_activity" | "ambient_audio" | "sleep" | "activity_recognition" | "health_connect" | "connectivity_state" | "app_network_usage" | "device_settings" | "time_use_diary" | "app_inventory" | "gaze_tracking" | "interaction_content" | "location" | "communication_log" | "hardware_sensors"
collectionModuleIds: [
  "usage_events",
  "in_app_activity_class",
  "device_lifecycle",
  "user_identification",
  "upload_telemetry",
  "sensor_availability",
  "questionnaire",
  "battery_telemetry",
  "sensor_accelerometer",
  "sensor_gyroscope",
  "sensor_magnetometer",
  "sensor_gravity",
  "sensor_linear_acceleration",
  "sensor_rotation_vector",
  "sensor_step_counter",
  "sensor_light",
  "sensor_proximity",
  "sensor_significant_motion",
  "sensor_tilt_detector",
  "sensor_screen_orientation",
  "sensor_samsung_grip_wifi",
  "sensor_samsung_motion",
  "interaction_events",
  "audio_activity",
  "audio_content",
  "notification_activity",
  "ambient_audio",
  "sleep",
  "activity_recognition",
  "health_connect",
  "connectivity_state",
  "app_network_usage",
  "device_settings",
  "time_use_diary",
  "app_inventory",
  "gaze_tracking",
  "interaction_content",
  "location",
  "communication_log",
  "hardware_sensors",
]

#AndroidSensorType: "accelerometer" | "gyroscope" | "magnetometer" | "gravity" | "linearAcceleration" | "rotationVector" | "stepCounter" | "light" | "proximity" | "significantMotion" | "tiltDetector" | "screenOrientation" | "samsungGripWifi" | "samsungMotion"
androidSensorTypes: [
  "accelerometer",
  "gyroscope",
  "magnetometer",
  "gravity",
  "linearAcceleration",
  "rotationVector",
  "stepCounter",
  "light",
  "proximity",
  "significantMotion",
  "tiltDetector",
  "screenOrientation",
  "samsungGripWifi",
  "samsungMotion",
]

#IosSensorType: "deviceUsage" | "keyboardMetrics" | "messagesUsage" | "phoneUsage" | "accelerometer" | "pedometer" | "motionActivity"
iosSensorTypes: [
  "deviceUsage",
  "keyboardMetrics",
  "messagesUsage",
  "phoneUsage",
  "accelerometer",
  "pedometer",
  "motionActivity",
]

#StudyFeature: "APP_USAGE" | "APP_USAGE_SURVEY" | "TIME_USE_DIARY" | "ARCHIVE" | "IOS_SENSOR" | "ANDROID_SENSOR" | "CHRONICLE_SURVEYS" | "CHRONICLE" | "CHRONICLE_DATA_COLLECTION"
studyFeatures: [
  "APP_USAGE",
  "APP_USAGE_SURVEY",
  "TIME_USE_DIARY",
  "ARCHIVE",
  "IOS_SENSOR",
  "ANDROID_SENSOR",
  "CHRONICLE_SURVEYS",
  "CHRONICLE",
  "CHRONICLE_DATA_COLLECTION",
]

#AuditAction: "LOGIN" | "LOGOUT" | "LOGIN_FAILED" | "TOKEN_REFRESH" | "SESSION_EXPIRED" | "VIEW" | "SEARCH" | "LIST" | "EXPORT" | "DOWNLOAD" | "CREATE" | "UPDATE" | "DELETE" | "ARCHIVE" | "RESTORE" | "PERMISSION_CHANGE" | "PERMISSION_GRANT" | "PERMISSION_REVOKE" | "SETTINGS_CHANGE" | "CONFIGURATION_CHANGE" | "UNAUTHORIZED_ACCESS" | "ACCESS_DENIED" | "INVALID_REQUEST" | "RATE_LIMITED" | "SUSPICIOUS_ACTIVITY" | "DATA_SUBMISSION" | "DEVICE_ENROLLMENT" | "DEVICE_UNENROLLMENT" | "SENSOR_DATA_UPLOAD" | "USAGE_DATA_UPLOAD" | "BATTERY_TELEMETRY_UPLOAD" | "INTERACTION_EVENTS_UPLOAD" | "COLLECTION_ACKNOWLEDGMENT" | "STUDY_CREATE" | "STUDY_UPDATE" | "STUDY_DELETE" | "PARTICIPANT_ENROLL" | "PARTICIPANT_WITHDRAW" | "PARTICIPANT_DATA_ACCESS" | "NOTIFICATION_SENT" | "NOTIFICATION_FAILED" | "JOB_CREATED" | "JOB_COMPLETED" | "JOB_FAILED" | "DATA_DELETION"
auditActions: [
  "LOGIN",
  "LOGOUT",
  "LOGIN_FAILED",
  "TOKEN_REFRESH",
  "SESSION_EXPIRED",
  "VIEW",
  "SEARCH",
  "LIST",
  "EXPORT",
  "DOWNLOAD",
  "CREATE",
  "UPDATE",
  "DELETE",
  "ARCHIVE",
  "RESTORE",
  "PERMISSION_CHANGE",
  "PERMISSION_GRANT",
  "PERMISSION_REVOKE",
  "SETTINGS_CHANGE",
  "CONFIGURATION_CHANGE",
  "UNAUTHORIZED_ACCESS",
  "ACCESS_DENIED",
  "INVALID_REQUEST",
  "RATE_LIMITED",
  "SUSPICIOUS_ACTIVITY",
  "DATA_SUBMISSION",
  "DEVICE_ENROLLMENT",
  "DEVICE_UNENROLLMENT",
  "SENSOR_DATA_UPLOAD",
  "USAGE_DATA_UPLOAD",
  "BATTERY_TELEMETRY_UPLOAD",
  "INTERACTION_EVENTS_UPLOAD",
  "COLLECTION_ACKNOWLEDGMENT",
  "STUDY_CREATE",
  "STUDY_UPDATE",
  "STUDY_DELETE",
  "PARTICIPANT_ENROLL",
  "PARTICIPANT_WITHDRAW",
  "PARTICIPANT_DATA_ACCESS",
  "NOTIFICATION_SENT",
  "NOTIFICATION_FAILED",
  "JOB_CREATED",
  "JOB_COMPLETED",
  "JOB_FAILED",
  "DATA_DELETION",
]
