global:
  scrape_interval: 15s

scrape_configs:
  - job_name: chronicle-backend
    metrics_path: /prometheus/
    basic_auth:
      username: chronicle-metrics
      password_file: /run/secrets/chronicle_security_metrics_password
    static_configs:
      - targets:
          - chronicle-backend:40320
        labels:
          service: chronicle
