apiVersion: v1
kind: ResourceQuota
metadata:
  name: resource-quota
  namespace: chronicle
spec:
  hard:
    requests.cpu: 1500m
    requests.memory: 5Gi
    limits.cpu: "5"
    limits.memory: 6Gi
    pods: "15"
    requests.storage: 200Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: chronicle-backend
  namespace: chronicle
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    spec:
      containers:
        - name: backend
          env:
            - name: CHRONICLE_SERVER_XMS
              value: -Xms512m
            - name: CHRONICLE_SERVER_XMX
              value: -Xmx2g
          resources:
            requests:
              cpu: 500m
              memory: 1536Mi
            limits:
              cpu: "2"
              memory: 3Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
  namespace: chronicle
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: keycloak
          resources:
            requests:
              cpu: 100m
              memory: 96Mi
            limits:
              cpu: 500m
              memory: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: chronicle-frontend
  namespace: chronicle
spec:
  replicas: 1
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: keycloak-postgres
  namespace: chronicle
spec:
  template:
    spec:
      containers:
        - name: postgres
          resources:
            requests:
              cpu: 25m
              memory: 48Mi
            limits:
              cpu: 250m
              memory: 384Mi
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
  namespace: chronicle
spec:
  template:
    spec:
      containers:
        - name: postgres
          resources:
            requests:
              cpu: 250m
              memory: 1Gi
            limits:
              cpu: "2"
              memory: 2Gi
