#!/usr/bin/env bash
# Idempotent: opens or updates a single 'freshness:jvm' issue per week.
# Reads the gradle-versions-plugin report and posts a markdown summary.
set -euo pipefail

report="${1:-build/dependencyUpdates/report.txt}"
if [ ! -f "$report" ]; then
    echo "ERROR: report not found: $report"
    exit 1
fi

repo="${REPO:-uzaira0/methodic}"
title="freshness:jvm — week of $(date -u +%Y-%m-%d)"

# Build markdown body from the report
body=$(cat <<MARKDOWN
# JVM Dependency Freshness — week of $(date -u +%Y-%m-%d)

Auto-generated by \`.github/workflows/freshness-jvm.yml\`. This issue is updated weekly.

## Summary

\`\`\`
$(awk '/The following dependencies have later milestone versions:/,/Gradle release-candidate updates/' "$report" | head -200)
\`\`\`

## What to do

For each entry above:
1. If patch + minor: dependabot may already have proposed a PR. Check open dependabot PRs.
2. If major: review the changelog, plan a migration, open a PR with the bump.
3. If declining to upgrade: comment in this issue with the reason and date.

## Verifier

To regenerate locally:
\`\`\`bash
./gradlew dependencyUpdates -Drevision=release
cat build/dependencyUpdates/report.txt
\`\`\`
MARKDOWN
)

# Find existing open freshness:jvm issue
existing=$(gh issue list --repo "$repo" --label "freshness:jvm" --state open \
    --json number --jq '.[0].number // empty')

if [ -n "$existing" ]; then
    echo "Updating existing issue #$existing"
    gh issue edit "$existing" --repo "$repo" --title "$title" --body "$body"
else
    echo "Creating new issue"
    # Ensure label exists
    gh label create "freshness:jvm" --repo "$repo" --color "0052CC" \
        --description "Weekly JVM dependency freshness report" 2>/dev/null || true
    gh issue create --repo "$repo" --title "$title" --body "$body" --label "freshness:jvm"
fi
