#!/usr/bin/env python3
"""Generate checked Chronicle contract artifacts from the LinkML schema."""

from __future__ import annotations

import argparse
import difflib
import hashlib
import json
import sys
from pathlib import Path
from typing import Any

import yaml


ROOT = Path(__file__).resolve().parents[1]
SCHEMA_PATH = ROOT / "ontology" / "chronicle.linkml.yaml"
OUTPUTS = {
    ROOT / "docs" / "generated" / "chronicle-contracts.md": "markdown",
    ROOT / "chronicle-web" / "src" / "modern" / "generated" / "chronicle-contracts.ts": "typescript",
    ROOT / "deploy" / "cue" / "chronicle_contracts.gen.cue": "cue",
    ROOT / "generated" / "domain-contracts" / "chronicle-domain-contracts.json": "domain-json",
}

TS_EXPORT_NAMES = {
    "DeploymentProfile": "DEPLOYMENT_PROFILES",
    "ObservabilityBackend": "OBSERVABILITY_BACKENDS",
    "SourceDeviceType": "SOURCE_DEVICE_TYPES",
    "ParticipantDataType": "PARTICIPANT_DATA_TYPES",
    "ParticipationStatus": "PARTICIPATION_STATUSES",
    "StudyLifecycleStatus": "STUDY_LIFECYCLE_STATUSES",
    "ConsentTrigger": "CONSENT_TRIGGERS",
    "CollectionDataDisposition": "COLLECTION_DATA_DISPOSITIONS",
    "CollectionPrivacyClass": "COLLECTION_PRIVACY_CLASSES",
    "CollectionModuleId": "COLLECTION_MODULE_IDS",
    "AndroidSensorType": "ANDROID_SENSOR_TYPES",
    "IosSensorType": "IOS_SENSOR_TYPES",
    "StudyFeature": "STUDY_FEATURES",
    "AuditAction": "AUDIT_ACTIONS",
}


def load_schema() -> dict:
    return yaml.safe_load(SCHEMA_PATH.read_text(encoding="utf-8"))


def source_sha256() -> str:
    return hashlib.sha256(SCHEMA_PATH.read_bytes()).hexdigest()


def generated_header(comment_prefix: str) -> list[str]:
    return [
        f"{comment_prefix} Generated by scripts/generate-chronicle-contracts.py from ontology/chronicle.linkml.yaml.",
        f"{comment_prefix} Source-SHA256: {source_sha256()}",
        f"{comment_prefix} Do not edit by hand.",
    ]


def enum_values(schema: dict, enum_name: str) -> list[tuple[str, str]]:
    values = schema["enums"][enum_name]["permissible_values"]
    out = []
    for value, body in values.items():
        description = ""
        if isinstance(body, dict):
            description = str(body.get("description") or "")
        out.append((str(value), description))
    return out


def enum_value_bodies(schema: dict, enum_name: str) -> list[tuple[str, dict[str, Any]]]:
    values = schema["enums"][enum_name]["permissible_values"]
    out = []
    for value, body in values.items():
        out.append((str(value), body if isinstance(body, dict) else {}))
    return out


def annotation(body: dict[str, Any], key: str) -> str | None:
    raw = (body.get("annotations") or {}).get(key)
    if isinstance(raw, dict):
        value = raw.get("value")
    else:
        value = raw
    if value is None:
        return None
    return str(value)


def annotation_bool(body: dict[str, Any], key: str) -> bool:
    value = annotation(body, key)
    if value is None:
        raise ValueError(f"Missing boolean annotation {key}")
    if value.lower() == "true":
        return True
    if value.lower() == "false":
        return False
    raise ValueError(f"Invalid boolean annotation {key}: {value}")


def annotation_int(body: dict[str, Any], key: str) -> int | None:
    value = annotation(body, key)
    return None if value is None else int(value)


def ts_string(value: str) -> str:
    return "'" + value.replace("\\", "\\\\").replace("'", "\\'") + "'"


def cue_string(value: str) -> str:
    return '"' + value.replace("\\", "\\\\").replace('"', '\\"') + '"'


def lower_camel_from_upper_snake(value: str) -> str:
    parts = value.lower().split("_")
    return parts[0] + "".join(part.capitalize() for part in parts[1:])


def render_typescript(schema: dict) -> str:
    # Header is prepended at the end so a Content-SHA256 of the body can be
    # stamped into it: chronicle-web's scripts/check-domain-contracts.ts
    # recomputes it to catch hand edits without a methodic checkout.
    lines = [""]

    for enum_name, export_name in TS_EXPORT_NAMES.items():
        values = [value for value, _ in enum_values(schema, enum_name)]
        single_line = f"export const {export_name} = [{', '.join(ts_string(value) for value in values)}] as const;"
        if len(single_line) <= 120:
            lines.append(single_line)
        else:
            lines.append(f"export const {export_name} = [")
            for value in values:
                lines.append(f"  {ts_string(value)},")
            lines.append("] as const;")
        lines.append(f"export type {enum_name} = (typeof {export_name})[number];")
        lines.append("")

    contract = domain_contract(schema)["contracts"]

    lines.extend(
        [
            "export type CollectionModuleContract = {",
            "  readonly enumName: string;",
            "  readonly id: CollectionModuleId;",
            "  readonly privacyClass: CollectionPrivacyClass;",
            "  readonly active: boolean;",
            "  readonly defaultEnabledOverride: boolean | null;",
            "  readonly defaultEnabled: boolean;",
            "  readonly androidSensorModule: boolean;",
            "  readonly activeDefaultEnabled: boolean;",
            "};",
            "",
            "export const COLLECTION_MODULE_CONTRACTS = [",
        ]
    )
    for module in contract["collectionModules"]:
        lines.extend(
            [
                "  {",
                f"    enumName: {ts_string(module['enumName'])},",
                f"    id: {ts_string(module['id'])},",
                f"    privacyClass: {ts_string(module['privacyClass'])},",
                f"    active: {str(module['active']).lower()},",
                "    defaultEnabledOverride: "
                + ("null" if module["defaultEnabledOverride"] is None else str(module["defaultEnabledOverride"]).lower())
                + ",",
                f"    defaultEnabled: {str(module['defaultEnabled']).lower()},",
                f"    androidSensorModule: {str(module['androidSensorModule']).lower()},",
                f"    activeDefaultEnabled: {str(module['activeDefaultEnabled']).lower()},",
                "  },",
            ]
        )
    lines.extend(
        [
            "] as const satisfies readonly CollectionModuleContract[];",
            "",
            "export type AndroidSensorMapping = {",
            "  readonly androidSensorType: AndroidSensorType;",
            "  readonly collectionModuleId: CollectionModuleId;",
            "  readonly collectionModuleEnum: string;",
            "  readonly active: boolean;",
            "  readonly displayOrder: number;",
            "};",
            "",
            "export const ANDROID_SENSOR_MAPPINGS = [",
        ]
    )
    for mapping in contract["androidSensorMappings"]:
        lines.extend(
            [
                "  {",
                f"    androidSensorType: {ts_string(mapping['androidSensorType'])},",
                f"    collectionModuleId: {ts_string(mapping['collectionModuleId'])},",
                f"    collectionModuleEnum: {ts_string(mapping['collectionModuleEnum'])},",
                f"    active: {str(mapping['active']).lower()},",
                f"    displayOrder: {mapping['displayOrder']},",
                "  },",
            ]
        )
    lines.extend(
        [
            "] as const satisfies readonly AndroidSensorMapping[];",
            "",
        ]
    )
    for export_name, type_name, values in [
        ("ACTIVE_COLLECTION_MODULE_IDS", "ActiveCollectionModuleId", contract["activeCollectionModuleIds"]),
        (
            "ACTIVE_DEFAULT_ENABLED_COLLECTION_MODULE_IDS",
            "ActiveDefaultEnabledCollectionModuleId",
            contract["activeDefaultEnabledCollectionModuleIds"],
        ),
        ("INACTIVE_COLLECTION_MODULE_IDS", "InactiveCollectionModuleId", contract["inactiveCollectionModuleIds"]),
        ("ANDROID_SENSOR_MODULE_IDS", "AndroidSensorModuleId", contract["androidSensorModuleIds"]),
    ]:
        lines.append(f"export const {export_name} = [")
        for value in values:
            lines.append(f"  {ts_string(value)},")
        lines.append("] as const;")
        lines.append(f"export type {type_name} = (typeof {export_name})[number];")
        lines.append("")

    # body starts with the blank separator line ("" head of `lines`), and is the
    # exact byte range chronicle-web's checker hashes: everything after the
    # "// Do not edit by hand.\n" line.
    body = "\n".join(lines)
    header = generated_header("//")
    header.insert(2, f"// Content-SHA256: {hashlib.sha256(body.encode('utf-8')).hexdigest()}")
    return "\n".join(header) + "\n" + body


def render_cue(schema: dict) -> str:
    lines = generated_header("//") + ["", "package chronicledeploy", ""]

    for enum_name, export_name in TS_EXPORT_NAMES.items():
        values = [value for value, _ in enum_values(schema, enum_name)]
        cue_values = " | ".join(cue_string(value) for value in values)
        cue_list_name = lower_camel_from_upper_snake(export_name)
        lines.append(f"#{enum_name}: {cue_values}")
        lines.append(f"{cue_list_name}: [")
        for value in values:
            lines.append(f"  {cue_string(value)},")
        lines.append("]")
        lines.append("")

    return "\n".join(lines)


def render_markdown(schema: dict) -> str:
    lines = [
        "# Chronicle Generated Contracts",
        "",
        "Generated by `scripts/generate-chronicle-contracts.py` from",
        "`ontology/chronicle.linkml.yaml`.",
        "",
        f"Source SHA-256: `{source_sha256()}`.",
        "",
        "Do not edit by hand.",
        "",
    ]

    for enum_name in TS_EXPORT_NAMES:
        enum_body = schema["enums"][enum_name]
        lines.extend([
            f"## {enum_name}",
            "",
            str(enum_body.get("description") or "").strip(),
            "",
            "| Value | Description |",
            "|-------|-------------|",
        ])
        for value, description in enum_values(schema, enum_name):
            lines.append(f"| `{value}` | {description} |")
        lines.append("")

    return "\n".join(lines)


def privacy_classes(schema: dict) -> list[dict[str, Any]]:
    return [
        {
            "name": value,
            "defaultEnabled": annotation_bool(body, "defaultEnabled"),
        }
        for value, body in enum_value_bodies(schema, "CollectionPrivacyClass")
    ]


def collection_modules(schema: dict) -> list[dict[str, Any]]:
    modules = []
    for value, body in enum_value_bodies(schema, "CollectionModuleId"):
        default_override = annotation(body, "defaultEnabledOverride")
        modules.append(
            {
                "enumName": annotation(body, "enumName") or value.upper(),
                "id": value,
                "privacyClass": annotation(body, "privacyClass"),
                "active": annotation_bool(body, "active"),
                "defaultEnabledOverride": None if default_override is None else default_override.lower() == "true",
                "defaultEnabled": annotation_bool(body, "defaultEnabled"),
                "androidSensorModule": annotation_bool(body, "androidSensorModule"),
                "activeDefaultEnabled": annotation_bool(body, "activeDefaultEnabled"),
            }
        )
    return modules


def android_sensor_mappings(schema: dict) -> list[dict[str, Any]]:
    mappings = []
    for value, body in enum_value_bodies(schema, "CollectionModuleId"):
        sensor_type = annotation(body, "androidSensorType")
        display_order = annotation_int(body, "sensorDisplayOrder")
        if sensor_type is None:
            continue
        mappings.append(
            {
                "androidSensorType": sensor_type,
                "collectionModuleId": value,
                "collectionModuleEnum": annotation(body, "enumName") or value.upper(),
                "active": annotation_bool(body, "active"),
                "displayOrder": display_order if display_order is not None else len(mappings),
            }
        )
    return sorted(mappings, key=lambda entry: entry["displayOrder"])


def collection_data_dispositions(schema: dict) -> list[dict[str, str]]:
    return [
        {
            "enumName": annotation(body, "enumName") or value.upper(),
            "id": value,
        }
        for value, body in enum_value_bodies(schema, "CollectionDataDisposition")
    ]


def domain_contract(schema: dict) -> dict[str, Any]:
    modules = collection_modules(schema)
    mappings = android_sensor_mappings(schema)
    return {
        "schemaVersion": "chronicle-domain-contracts/v1",
        "generatedBy": "scripts/generate-chronicle-contracts.py",
        "manualEdit": False,
        "sourceRepo": "methodic",
        "sourceFiles": {
            "linkml": {
                "path": "ontology/chronicle.linkml.yaml",
                "sha256": source_sha256(),
            },
        },
        "contracts": {
            "collectionModules": modules,
            "activeCollectionModuleIds": [module["id"] for module in modules if module["active"]],
            "activeDefaultEnabledCollectionModuleIds": [
                module["id"] for module in modules if module["activeDefaultEnabled"]
            ],
            "inactiveCollectionModuleIds": [module["id"] for module in modules if not module["active"]],
            "androidSensorModuleIds": [module["id"] for module in modules if module["androidSensorModule"]],
            "privacyClasses": privacy_classes(schema),
            "androidSensorTypes": [value for value, _ in enum_values(schema, "AndroidSensorType")],
            "androidSensorMappings": mappings,
            "iosSensorTypes": [value for value, _ in enum_values(schema, "IosSensorType")],
            "studyFeatures": [value for value, _ in enum_values(schema, "StudyFeature")],
            "participantDataTypes": [value for value, _ in enum_values(schema, "ParticipantDataType")],
            "participationStatuses": [value for value, _ in enum_values(schema, "ParticipationStatus")],
            "studyLifecycleStatuses": [value for value, _ in enum_values(schema, "StudyLifecycleStatus")],
            "consentTriggers": [value for value, _ in enum_values(schema, "ConsentTrigger")],
            "collectionDataDispositions": collection_data_dispositions(schema),
        },
        "compatibility": {
            "unknownCollectionModuleIds": "Consumers that support tolerant settings decode should ignore unknown module ids.",
            "inactiveCollectionModuleIds": "Inactive ids are decode-compatible and must not be offered as active collection modules.",
            "generatedConsumers": "Generated consumers must preserve unknown-value handling appropriate to their platform boundary.",
        },
    }


def render_domain_json(schema: dict) -> str:
    return json.dumps(domain_contract(schema), indent=2) + "\n"


def expected_outputs(schema: dict) -> dict[Path, str]:
    return {
        path: (
            render_markdown(schema)
            if kind == "markdown"
            else render_typescript(schema)
            if kind == "typescript"
            else render_cue(schema)
            if kind == "cue"
            else render_domain_json(schema)
        )
        for path, kind in OUTPUTS.items()
    }


def check_outputs(outputs: dict[Path, str]) -> int:
    failed = False
    for path, expected in outputs.items():
        actual = path.read_text(encoding="utf-8") if path.exists() else ""
        if actual != expected:
            failed = True
            print(f"{path.relative_to(ROOT)} is stale", file=sys.stderr)
            diff = difflib.unified_diff(
                actual.splitlines(),
                expected.splitlines(),
                fromfile=str(path.relative_to(ROOT)),
                tofile=f"{path.relative_to(ROOT)} (expected)",
                lineterm="",
            )
            for line in diff:
                print(line, file=sys.stderr)
    return 1 if failed else 0


def write_outputs(outputs: dict[Path, str]) -> None:
    for path, content in outputs.items():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8")
        print(f"wrote {path.relative_to(ROOT)}")


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="fail if generated contract artifacts are stale")
    args = parser.parse_args()

    outputs = expected_outputs(load_schema())
    if args.check:
        return check_outputs(outputs)
    write_outputs(outputs)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
