apiVersion: v1
kind: ServiceAccount
metadata:
  name: chronicle-backend
  namespace: chronicle
  labels:
    app.kubernetes.io/name: chronicle-backend
    app.kubernetes.io/part-of: chronicle
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: chronicle-frontend
  namespace: chronicle
  labels:
    app.kubernetes.io/name: chronicle-frontend
    app.kubernetes.io/part-of: chronicle
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: chronicle-postgres
  namespace: chronicle
  labels:
    app.kubernetes.io/name: chronicle-postgres
    app.kubernetes.io/part-of: chronicle
automountServiceAccountToken: false
